env:
  global:
    - CC_TEST_REPORTER_ID=e0cc4ba3614abde2c3b7de0eb0343f0eb2538d0d32038774d9c0e78935018140
language: ruby
rvm:
- 2.5.0
before_install:
  - gem install bundler
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle install
script: bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT